version: '3.9'
services:
  react_pwa:
    container_name: react_pwa
    image: node:alpine
    working_dir: /home/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
    - 3000:3000
    volumes:
    - ./app:/home/app